// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostInfoStatusApplyConfiguration represents a declarative configuration of the HostInfoStatus type for use
// with apply.
//
// HostInfoStatus reports the detected host hardware limits.
type HostInfoStatusApplyConfiguration struct {
	// cpus is the number of logical CPUs on the host.
	CPUs *int `json:"cpus,omitempty"`
	// memory is the total host RAM in bytes.
	Memory *int64 `json:"memory,omitempty"`
}

// HostInfoStatusApplyConfiguration constructs a declarative configuration of the HostInfoStatus type for use with
// apply.
func HostInfoStatus() *HostInfoStatusApplyConfiguration {
	return &HostInfoStatusApplyConfiguration{}
}

// WithCPUs sets the CPUs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPUs field is set to the value of the last call.
func (b *HostInfoStatusApplyConfiguration) WithCPUs(value int) *HostInfoStatusApplyConfiguration {
	b.CPUs = &value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *HostInfoStatusApplyConfiguration) WithMemory(value int64) *HostInfoStatusApplyConfiguration {
	b.Memory = &value
	return b
}
