// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// ComposeProjectMemberApplyConfiguration represents a declarative configuration of the ComposeProjectMember type for use
// with apply.
//
// ComposeProjectMember describes a single member of a compose project, which is
// a container, image, or volume.
type ComposeProjectMemberApplyConfiguration struct {
	// Name is the name of the member object, in the form [kind]/[name], e.g.
	// "Volume/myvolume".
	Name *string `json:"name,omitempty"`
	// UID is the UID of the member object.
	UID *types.UID `json:"uid,omitempty"`
}

// ComposeProjectMemberApplyConfiguration constructs a declarative configuration of the ComposeProjectMember type for use with
// apply.
func ComposeProjectMember() *ComposeProjectMemberApplyConfiguration {
	return &ComposeProjectMemberApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ComposeProjectMemberApplyConfiguration) WithName(value string) *ComposeProjectMemberApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ComposeProjectMemberApplyConfiguration) WithUID(value types.UID) *ComposeProjectMemberApplyConfiguration {
	b.UID = &value
	return b
}
