// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ComposeProjectSpecApplyConfiguration represents a declarative configuration of the ComposeProjectSpec type for use
// with apply.
//
// ComposeProjectSpec defines the identity of a `docker compose` project.
// The information here cannot recreate a running project (profile selection
// and environment variables set at `compose up` time are not available), so
// changing the spec does not automatically update the project; actions must
// be requested explicitly via the AnnotationAction annotation.
type ComposeProjectSpecApplyConfiguration struct {
	// Namespace is the container namespace; refers to a `ContainerNamespace`
	// object in the same Kubernetes namespace. Immutable once created.
	Namespace *string `json:"namespace,omitempty"`
	// Name is the compose project name. Immutable once created.
	Name *string `json:"name,omitempty"`
	// WorkingDir is the compose project directory on the host (i.e. relative
	// to where the RDD process runs). Used to look up any files needed. May
	// be unset for a ComposeProject that was automatically created from
	// observed containers or volumes.
	WorkingDir *string `json:"workingDir,omitempty"`
	// Configs is the list of compose files used to create the project,
	// relative to WorkingDir. It is not guaranteed that this is sufficient to
	// recreate the project. May be unset for a ComposeProject that was
	// automatically created from observed containers or volumes.
	Configs []string `json:"configs,omitempty"`
}

// ComposeProjectSpecApplyConfiguration constructs a declarative configuration of the ComposeProjectSpec type for use with
// apply.
func ComposeProjectSpec() *ComposeProjectSpecApplyConfiguration {
	return &ComposeProjectSpecApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ComposeProjectSpecApplyConfiguration) WithNamespace(value string) *ComposeProjectSpecApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ComposeProjectSpecApplyConfiguration) WithName(value string) *ComposeProjectSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithWorkingDir sets the WorkingDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkingDir field is set to the value of the last call.
func (b *ComposeProjectSpecApplyConfiguration) WithWorkingDir(value string) *ComposeProjectSpecApplyConfiguration {
	b.WorkingDir = &value
	return b
}

// WithConfigs adds the given value to the Configs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Configs field.
func (b *ComposeProjectSpecApplyConfiguration) WithConfigs(values ...string) *ComposeProjectSpecApplyConfiguration {
	for i := range values {
		b.Configs = append(b.Configs, values[i])
	}
	return b
}
