// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ComposeStatusApplyConfiguration represents a declarative configuration of the ComposeStatus type for use
// with apply.
//
// ComposeStatus defines the observed state of a `docker compose` project.
type ComposeStatusApplyConfiguration struct {
	// Namespace is the container namespace; refers to a [ContainerNamespace]
	// object in the same Kubernetes namespace.
	Namespace *string `json:"namespace,omitempty"`
	// Name is the compose project name.
	Name *string `json:"name,omitempty"`
	// WorkingDir is the compose project directory on the host (i.e. relative
	// to where the RDD process runs). May be unset for a Compose object that
	// was automatically created from observed containers, images, or
	// volumes rather than a [ComposeUpRequest].
	WorkingDir *string `json:"workingDir,omitempty"`
	// Configs is the list of compose files used to create the project,
	// relative to WorkingDir. It is not guaranteed that this is sufficient to
	// recreate the project. May be unset for a Compose object that was
	// automatically created from observed containers, images, or volumes.
	Configs []string `json:"configs,omitempty"`
	// Members tracks the objects that are part of the compose project. The
	// name is a combination of object kind and name, e.g. "Volume/myvolume".
	// The UID is also tracked.
	Members []ComposeMemberApplyConfiguration `json:"members,omitempty"`
	// Conditions represent the state of the compose project.
	// Known condition types include:
	//
	// - "HasMembers": The compose project has at least one member.
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ComposeStatusApplyConfiguration constructs a declarative configuration of the ComposeStatus type for use with
// apply.
func ComposeStatus() *ComposeStatusApplyConfiguration {
	return &ComposeStatusApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ComposeStatusApplyConfiguration) WithNamespace(value string) *ComposeStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ComposeStatusApplyConfiguration) WithName(value string) *ComposeStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithWorkingDir sets the WorkingDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkingDir field is set to the value of the last call.
func (b *ComposeStatusApplyConfiguration) WithWorkingDir(value string) *ComposeStatusApplyConfiguration {
	b.WorkingDir = &value
	return b
}

// WithConfigs adds the given value to the Configs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Configs field.
func (b *ComposeStatusApplyConfiguration) WithConfigs(values ...string) *ComposeStatusApplyConfiguration {
	for i := range values {
		b.Configs = append(b.Configs, values[i])
	}
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *ComposeStatusApplyConfiguration) WithMembers(values ...*ComposeMemberApplyConfiguration) *ComposeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ComposeStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ComposeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
