// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// ComposeMemberApplyConfiguration represents a declarative configuration of the ComposeMember type for use
// with apply.
//
// ComposeMember describes a single member of a compose project, which is a
// container, image, or volume.
type ComposeMemberApplyConfiguration struct {
	// Name is the name of the member object, in the form [kind]/[name], e.g.
	// "Volume/myvolume".
	Name *string `json:"name,omitempty"`
	// UID is the UID of the member object.
	UID *types.UID `json:"uid,omitempty"`
}

// ComposeMemberApplyConfiguration constructs a declarative configuration of the ComposeMember type for use with
// apply.
func ComposeMember() *ComposeMemberApplyConfiguration {
	return &ComposeMemberApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ComposeMemberApplyConfiguration) WithName(value string) *ComposeMemberApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ComposeMemberApplyConfiguration) WithUID(value types.UID) *ComposeMemberApplyConfiguration {
	b.UID = &value
	return b
}
