// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ComposeProjectStatusApplyConfiguration represents a declarative configuration of the ComposeProjectStatus type for use
// with apply.
//
// ComposeProjectStatus defines the observed state of the compose project.
type ComposeProjectStatusApplyConfiguration struct {
	// LastAction records the most recent action requested via the
	// AnnotationAction annotation and its outcome. Persists after the action
	// completes until overwritten by the next action.
	LastAction *ComposeProjectLastActionApplyConfiguration `json:"lastAction,omitempty"`
	// Members tracks the objects that are part of the compose project.  The name
	// is a combination of object kind and name, e.g. "Volume/myvolume".  The UID
	// is also tracked.
	Members []ComposeProjectMemberApplyConfiguration `json:"members,omitempty"`
	// Conditions represent the state of the compose project.
	// Known condition types include:
	// - "Settled": The compose project is at a steady state.
	// - "HasMembers": The compose project has at least one member.
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ComposeProjectStatusApplyConfiguration constructs a declarative configuration of the ComposeProjectStatus type for use with
// apply.
func ComposeProjectStatus() *ComposeProjectStatusApplyConfiguration {
	return &ComposeProjectStatusApplyConfiguration{}
}

// WithLastAction sets the LastAction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastAction field is set to the value of the last call.
func (b *ComposeProjectStatusApplyConfiguration) WithLastAction(value *ComposeProjectLastActionApplyConfiguration) *ComposeProjectStatusApplyConfiguration {
	b.LastAction = value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *ComposeProjectStatusApplyConfiguration) WithMembers(values ...*ComposeProjectMemberApplyConfiguration) *ComposeProjectStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ComposeProjectStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ComposeProjectStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
